version: 1

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/php:7.3-node-browsers
    - image: circleci/mysql:5.7
  environment:
    - AWS_REGION: ap-northeast-1
    - APP_DEBUG: true
    - APP_KEY: base64:
    - DB_DATABASE: circle_test
    - DB_USERNAME: root
    - MYSQL_ALLOW_EMPTY_PASSWORD: true

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
        name: install pdo_mysql
        command:
          sudo apt update
          sudo docker-php-ext-install pdo_mysql
          sudo docker-php-ext-enable pdo_mysql
